/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BreakdownCreateNestedManyWithoutMachinesInput } from "./BreakdownCreateNestedManyWithoutMachinesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { MaintenanceCreateNestedManyWithoutMachinesInput } from "./MaintenanceCreateNestedManyWithoutMachinesInput";
import { MaintenanceScheduleCreateNestedManyWithoutMachinesInput } from "./MaintenanceScheduleCreateNestedManyWithoutMachinesInput";

@InputType()
class MachineCreateInput {
  @ApiProperty({
    required: false,
    type: () => BreakdownCreateNestedManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => BreakdownCreateNestedManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => BreakdownCreateNestedManyWithoutMachinesInput, {
    nullable: true,
  })
  breakdowns?: BreakdownCreateNestedManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: () => MaintenanceCreateNestedManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => MaintenanceCreateNestedManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => MaintenanceCreateNestedManyWithoutMachinesInput, {
    nullable: true,
  })
  maintenances?: MaintenanceCreateNestedManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: () => MaintenanceScheduleCreateNestedManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => MaintenanceScheduleCreateNestedManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => MaintenanceScheduleCreateNestedManyWithoutMachinesInput, {
    nullable: true,
  })
  maintenanceSchedules?: MaintenanceScheduleCreateNestedManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  modelNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;
}

export { MachineCreateInput as MachineCreateInput };
