/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BreakdownReportCreateNestedManyWithoutMachinesInput } from "./BreakdownReportCreateNestedManyWithoutMachinesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { MaintenanceReportCreateNestedManyWithoutMachinesInput } from "./MaintenanceReportCreateNestedManyWithoutMachinesInput";
import { MaintenanceScheduleCreateNestedManyWithoutMachinesInput } from "./MaintenanceScheduleCreateNestedManyWithoutMachinesInput";

@InputType()
class MachineCreateInput {
  @ApiProperty({
    required: false,
    type: () => BreakdownReportCreateNestedManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => BreakdownReportCreateNestedManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => BreakdownReportCreateNestedManyWithoutMachinesInput, {
    nullable: true,
  })
  breakdowns?: BreakdownReportCreateNestedManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: () => MaintenanceReportCreateNestedManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => MaintenanceReportCreateNestedManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => MaintenanceReportCreateNestedManyWithoutMachinesInput, {
    nullable: true,
  })
  maintenances?: MaintenanceReportCreateNestedManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: () => MaintenanceScheduleCreateNestedManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => MaintenanceScheduleCreateNestedManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => MaintenanceScheduleCreateNestedManyWithoutMachinesInput, {
    nullable: true,
  })
  maintenanceSchedules?: MaintenanceScheduleCreateNestedManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  modelNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;
}

export { MachineCreateInput as MachineCreateInput };
