/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BreakdownReportUpdateManyWithoutMachinesInput } from "./BreakdownReportUpdateManyWithoutMachinesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { MaintenanceReportUpdateManyWithoutMachinesInput } from "./MaintenanceReportUpdateManyWithoutMachinesInput";
import { MaintenanceScheduleUpdateManyWithoutMachinesInput } from "./MaintenanceScheduleUpdateManyWithoutMachinesInput";

@InputType()
class MachineUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BreakdownReportUpdateManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => BreakdownReportUpdateManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => BreakdownReportUpdateManyWithoutMachinesInput, {
    nullable: true,
  })
  breakdowns?: BreakdownReportUpdateManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: () => MaintenanceReportUpdateManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => MaintenanceReportUpdateManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => MaintenanceReportUpdateManyWithoutMachinesInput, {
    nullable: true,
  })
  maintenances?: MaintenanceReportUpdateManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: () => MaintenanceScheduleUpdateManyWithoutMachinesInput,
  })
  @ValidateNested()
  @Type(() => MaintenanceScheduleUpdateManyWithoutMachinesInput)
  @IsOptional()
  @Field(() => MaintenanceScheduleUpdateManyWithoutMachinesInput, {
    nullable: true,
  })
  maintenanceSchedules?: MaintenanceScheduleUpdateManyWithoutMachinesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  modelNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;
}

export { MachineUpdateInput as MachineUpdateInput };
