/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BreakdownReportService } from "../breakdownReport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BreakdownReportCreateInput } from "./BreakdownReportCreateInput";
import { BreakdownReport } from "./BreakdownReport";
import { BreakdownReportFindManyArgs } from "./BreakdownReportFindManyArgs";
import { BreakdownReportWhereUniqueInput } from "./BreakdownReportWhereUniqueInput";
import { BreakdownReportUpdateInput } from "./BreakdownReportUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BreakdownReportControllerBase {
  constructor(
    protected readonly service: BreakdownReportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BreakdownReport })
  @nestAccessControl.UseRoles({
    resource: "BreakdownReport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BreakdownReportCreateInput,
  })
  async createBreakdownReport(
    @common.Body() data: BreakdownReportCreateInput
  ): Promise<BreakdownReport> {
    return await this.service.createBreakdownReport({
      data: {
        ...data,

        machine: data.machine
          ? {
              connect: data.machine,
            }
          : undefined,
      },
      select: {
        breakdownDate: true,
        createdAt: true,
        description: true,
        id: true,

        machine: {
          select: {
            id: true,
          },
        },

        reporter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BreakdownReport] })
  @ApiNestedQuery(BreakdownReportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BreakdownReport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async breakdownReports(
    @common.Req() request: Request
  ): Promise<BreakdownReport[]> {
    const args = plainToClass(BreakdownReportFindManyArgs, request.query);
    return this.service.breakdownReports({
      ...args,
      select: {
        breakdownDate: true,
        createdAt: true,
        description: true,
        id: true,

        machine: {
          select: {
            id: true,
          },
        },

        reporter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BreakdownReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BreakdownReport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async breakdownReport(
    @common.Param() params: BreakdownReportWhereUniqueInput
  ): Promise<BreakdownReport | null> {
    const result = await this.service.breakdownReport({
      where: params,
      select: {
        breakdownDate: true,
        createdAt: true,
        description: true,
        id: true,

        machine: {
          select: {
            id: true,
          },
        },

        reporter: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BreakdownReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BreakdownReport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BreakdownReportUpdateInput,
  })
  async updateBreakdownReport(
    @common.Param() params: BreakdownReportWhereUniqueInput,
    @common.Body() data: BreakdownReportUpdateInput
  ): Promise<BreakdownReport | null> {
    try {
      return await this.service.updateBreakdownReport({
        where: params,
        data: {
          ...data,

          machine: data.machine
            ? {
                connect: data.machine,
              }
            : undefined,
        },
        select: {
          breakdownDate: true,
          createdAt: true,
          description: true,
          id: true,

          machine: {
            select: {
              id: true,
            },
          },

          reporter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BreakdownReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BreakdownReport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBreakdownReport(
    @common.Param() params: BreakdownReportWhereUniqueInput
  ): Promise<BreakdownReport | null> {
    try {
      return await this.service.deleteBreakdownReport({
        where: params,
        select: {
          breakdownDate: true,
          createdAt: true,
          description: true,
          id: true,

          machine: {
            select: {
              id: true,
            },
          },

          reporter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
