/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BreakdownService } from "../breakdown.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BreakdownCreateInput } from "./BreakdownCreateInput";
import { Breakdown } from "./Breakdown";
import { BreakdownFindManyArgs } from "./BreakdownFindManyArgs";
import { BreakdownWhereUniqueInput } from "./BreakdownWhereUniqueInput";
import { BreakdownUpdateInput } from "./BreakdownUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BreakdownControllerBase {
  constructor(
    protected readonly service: BreakdownService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Breakdown })
  @nestAccessControl.UseRoles({
    resource: "Breakdown",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BreakdownCreateInput,
  })
  async createBreakdown(
    @common.Body() data: BreakdownCreateInput
  ): Promise<Breakdown> {
    return await this.service.createBreakdown({
      data: {
        ...data,

        machine: data.machine
          ? {
              connect: data.machine,
            }
          : undefined,
      },
      select: {
        breakdownDate: true,
        createdAt: true,
        description: true,
        id: true,

        machine: {
          select: {
            id: true,
          },
        },

        reporter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Breakdown] })
  @ApiNestedQuery(BreakdownFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Breakdown",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async breakdowns(@common.Req() request: Request): Promise<Breakdown[]> {
    const args = plainToClass(BreakdownFindManyArgs, request.query);
    return this.service.breakdowns({
      ...args,
      select: {
        breakdownDate: true,
        createdAt: true,
        description: true,
        id: true,

        machine: {
          select: {
            id: true,
          },
        },

        reporter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Breakdown })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Breakdown",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async breakdown(
    @common.Param() params: BreakdownWhereUniqueInput
  ): Promise<Breakdown | null> {
    const result = await this.service.breakdown({
      where: params,
      select: {
        breakdownDate: true,
        createdAt: true,
        description: true,
        id: true,

        machine: {
          select: {
            id: true,
          },
        },

        reporter: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Breakdown })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Breakdown",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BreakdownUpdateInput,
  })
  async updateBreakdown(
    @common.Param() params: BreakdownWhereUniqueInput,
    @common.Body() data: BreakdownUpdateInput
  ): Promise<Breakdown | null> {
    try {
      return await this.service.updateBreakdown({
        where: params,
        data: {
          ...data,

          machine: data.machine
            ? {
                connect: data.machine,
              }
            : undefined,
        },
        select: {
          breakdownDate: true,
          createdAt: true,
          description: true,
          id: true,

          machine: {
            select: {
              id: true,
            },
          },

          reporter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Breakdown })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Breakdown",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBreakdown(
    @common.Param() params: BreakdownWhereUniqueInput
  ): Promise<Breakdown | null> {
    try {
      return await this.service.deleteBreakdown({
        where: params,
        select: {
          breakdownDate: true,
          createdAt: true,
          description: true,
          id: true,

          machine: {
            select: {
              id: true,
            },
          },

          reporter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
